---
name: Package and release

"on":
  push:
    tags:
      - '**'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0  # full history for changelog

      - name: Package and release
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        uses: BigWigsMods/packager@e50a250f8705041e40f2fa1ddcb280a686d65aa0  # v2.6.1
        with:
          args: -n "{package-name}-{project-version}"
